# Generated by Django 5.0.2 on 2024-03-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_alter_order_delivery_crew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.SlugField(max_length=255),
        ),
    ]
